# config/model/lstm.yaml
type: lstm

# Model parameters as specified in Table 1
input_size: 431  # Number of neurons
hidden_size: 64
num_layers: 2
num_classes: 3
dropout: 0.3

# Sequence length is 10 for LSTM as mentioned in the paper
sequence_length: 16

# Task weights
task_weights:
  multiclass: 1.0
  contralateral: 1.0
  ipsilateral: 1.0