# Training parameters
epochs: 500
batch_size: 32
learning_rate: 0.0001
weight_decay: 0.00003  # Increased L2 regularization
gradient_clip_val: 1.0
early_stopping_patience: 5

# Sequence parameters
sequence_length: 32
overlap: 16

# Regularization
use_class_weights: true